simbricks/simbricks

- experiments/pyexps/ae/f1_dctcp.py
- experiments/pyexps/ae/f7_scale.py
- experiments/pyexps/ae/no_simbricks.py
- experiments/pyexps/ae/no_traffic.py
- experiments/pyexps/ae/nopaxos.py
- experiments/pyexps/ae/t1_netperf.py
- experiments/pyexps/dctcp.py
- experiments/pyexps/dist_memcache.py
- experiments/pyexps/dist_multinet.py
- experiments/pyexps/dist_netperf.py
- experiments/pyexps/femutest.py
- experiments/pyexps/modetcp.py
- experiments/pyexps/netperf.py
- experiments/pyexps/no_simbricks.py
- experiments/pyexps/no_traffic.py
- experiments/pyexps/nopaxos.py
- experiments/pyexps/pci_validation.py
- experiments/pyexps/scale_host.py
- experiments/pyexps/scale_load.py
- experiments/run.py
- experiments/simbricks/exectools.py
- experiments/simbricks/experiments.py
- experiments/simbricks/nodeconfig.py
- experiments/simbricks/proxy.py
- experiments/simbricks/simulator_utils.py
- experiments/simbricks/simulators.py
Having a mutable default value for a class variable is dangerous, as the mutable default value will be shared across all instances. See [here](https://docs.python.org/3/library/dataclasses.html#mutable-default-values) for more information. I did exactly this mistake in https://github.com/simbricks/simbricks/pull/21, which means that most experiments are currently failing to even start up the simulators. To prevent this issue in the future and not have a mixture of declaring class attributes in two different places (as class or instance variable), I moved everything to `__init__`.
Additionally, I fixed a typo in the class `NICSim`, which led to the i40e simulator being stuck at timestamp 500.
I tested the netperf experiment in the configuration `qemu-switch-i40e` and it is now producing …
> fix experiments no longer working

- experiments/simbricks/experiments.py
- experiments/simbricks/runtime/distributed.py
Fixes the remaining remark in #25. `pytype` currently seems buggy when using Generics for type annotation. It behaves as if we specified `Any` for the type of an class attribute meaning that it doesn't check anything. To solve this, I replaced the use of Generics with overriding the type of the attribute in the subclass.
I also investigated using `pyright` or `mytype`. Both face the issue that they report errors on code that actually has correct dynamic behavior doesn't necessarily use any incomprehensible Python trickery to do so. The fix for many of these errors is to add more code which does not ease understanding. It therefore makes sense to stick with pytype and hack our way around this issue.
> fix pytype not detecting broken auto_dist()

- experiments/simbricks/simulators.py
Forgot the curly braces when reformatting parameters passed to wirenet to use f-strings in #21. Should fix #31.
> fix wirenet not connecting to second socket

- sims/nic/i40e_bm/i40e_bm.cc
- sims/nic/i40e_bm/i40e_bm.h
- sims/nic/i40e_bm/i40e_lan.cc
- sims/nic/i40e_bm/i40e_queues.cc
- sims/nic/i40e_bm/logger.cc
Depending on the order some of the constructors get executed, instances of the logger can end up with a null pointer for the runner. This led to a segfault when calling TimePs() on that nullptr.
Here we fix this in two steps: first the logger takes a device pointer, which in turn contains a pointer to the runner that will eventually be initialized. Also fix up the logger to simply use 0 as a timestamp for log events before the runner is there.
> sims/nic/i40e_bm: fix logger segfault due to constructors

- experiments/simbricks/orchestration/exectools.py
- experiments/simbricks/orchestration/runtime/distributed.py
- experiments/simbricks/orchestration/runtime/local.py
drastically speeds up simulation performance in the presence of a lot of output
> orchestration: eliminate unnecessary output buffer copies

- sims/external/rules.mk
this gets rid of the non-fatal build error 'No names found, cannot describe anything'
> QEMU: set pkgversion string to 'SimBricks'

- images/scripts/install-base.sh
At the moment, only hot-fixes #75. I still have to work on a proper solution for setting the necessary kernel boot parameters to run experiments for Simics.
> hot-fix build process for images derived from base failing

- docker/Dockerfile.base
- docker/cleanup_images.sh
- docker/cleanup_ns3.sh
This fixes the `docker/cleanup_images.sh` script that partly broke after updating the kernel version in c64d3d0. It no longer removed the linux kernel source folder, since it still used the old version number. I switched to using a regex to avoid this issue in the future.
Additionally, this adds a cleanup script for ns-3 similar to those for qemu and gem5, as requested in #9.
> cleanup docker builds

- experiments/simbricks/orchestration/experiment/experiment_environment.py
- experiments/simbricks/orchestration/simulators.py
- experiments/simbricks/utils/__init__.py
- experiments/simbricks/utils/modify_gem5_cp_tick.py
Currently, when a checkpoint is created in gem5 using the KVM CPU, the simulated tick when the checkpoint is taken will end up in the few seconds or more when the KVM CPU is slow. When the checkpoint is afterwards restored, gem5 will continue the simulation at this tick. This means that other, synchronized simulators first have to catch up, essentially just synchronizing without performing any useful work. Depending on their speed, this can take a lot of time and is especially costly with a RTL simulator in the loop. To avoid this we now, by default, edit the to be restored gem5 checkpoint to start at tick 0 instead.
> orchestration/simulators.py: speed up experiments that use gem5 checkpoints

- experiments/simbricks/orchestration/runners.py
So far, simulator instances not connected to any other instances were skipped accidentally when creating the graph. So if a simbricks config only includes a single instance, e.g. a gem5 then it just does not get run at all. This fixes the problem and makes sure even simulators without connections get added to the dependency graph used to figure out the order for running simulators.
> orchestration: also run simulator instances without dependencies

- experiments/run.py
This makes it easier to use simbricks-run outside of the simbricks tree in the container. E.g. for other projects that use the simbricks image to run tests/experiments in their repo. The path can still be manually overridden when needed by specifying `simbricks-run --repo=FOO`.
> docker/simbricks-run: enable out of tree runs

- experiments/simbricks/orchestration/exectools.py
- experiments/simbricks/orchestration/runners.py
- experiments/simbricks/orchestration/runtime/local.py
This was a funny one 😄
Basically, on almost every machine, our orchestration framework got stuck trying to terminate our `i40e_bm`. I was able to observe this in our containers but not on my local machine. The reason for that is actually that I'm using Python 3.11 and they decided to change something important about [`asyncio.wait_for()`](https://docs.python.org/3/library/asyncio-task.html#asyncio.wait_for):
> Changed in version 3.11: Raises TimeoutError instead of asyncio.TimeoutError
So this meant that we caught the wrong exception in `Component.int_term_kill()`. The reason we didn't spot this earlier is that exceptions were swallowed by the call to `asyncio.wait()` in `runners.py:ExperimentBaseRunner.terminate_collect_sims()` when invoking `int_term_kill()`. Instead, we now also use …
> orchestration/exectools.py: fix getting stuck on terminating components

- lib/simbricks/base/if.c
Check the length of socket paths in SimbricksBaseIfListen and SimbricksBaseIfConnect. If the length exceeds the size of sun_path in the sockaddr_un struct, we fail with a meaningful error message.
This resolves #42.
> check length of socket paths in SimbricksBaseIfListen and SimbricksBaseIfConnect

- README.md
- doc/simulators/gem5.rst
- doc/user/troubleshooting.rst
This is long overdue and we are frequently getting questions about this, e.g. #93
> README, docs: clearly document how to avoid gem5 perf attach panic

- experiments/simbricks/orchestration/experiment/experiment_output.py
This allows the produced output JSON files to be immediately opened by text editors. So far, everything is dumped without white-space into a single line, which for example makes VS Code crash on sufficiently large files.
I tested this for a bit now and didn't notice a subjective difference in writing the JSON output files after interrupting an experiment.
> dump formatted JSON for experiments

- experiments/simbricks/orchestration/experiment/experiment_environment.py
- experiments/simbricks/orchestration/nodeconfig.py
ExpEnv: `hd_path` and `hd_path_raw` check if an absolute path is given as argument. This is set by using a nodeconfigs `disk_image` property. In case an absolute path is passed, it is returned unmodified. Otherwise the usual SimBricks image name resolution takes place.
> orchestration: absolue path check images

- lib/simbricks/axi/axi_subordinate.hh
- lib/simbricks/axi/axil_manager.hh
We need AXI adapters for every piece of RTL that we are simulating with Verilator, e.g. Corundum, VTA, and the JPEG decoder. This PR adds a clean C++ library that _should_ properly respect the AXI standard, something that is not true about the hacked-up solutions we employ so far. The current solutions also don't respect the semantics of non-blocking assignments, which leads to many unpredictable issues we already have to hack around.
This AXI library also generalizes to any data, address and ID bus width. Overall, I tried to keep things simple, which might mean that we need to add small additional features in the future like supporting other modes besides incremental bursts and actually using the `wstrb` values. For the accelerators I looked at (JPEG decoder, VTA) all features are …
> C++ AXI adapter library for RTL simulations

- lib/simbricks/base/if.h
The doc string says to return 1 in the case of an unnecessary sync, which the implementation actually doesn't do. It instead considers an unnecessary sync as success, which is generally also the intended behavior.
> lib/simbricks/base/if.h: fix docstring for SimBricksBaseIfOutSync()

- docker/cleanup_gem5.sh
- experiments/simbricks/orchestration/simulators.py
- sims/external/rules.mk
This updates the submodule pointer to the new gem5 version.
Note that this temporarily drops support for DDIO and the L3 cache, both of which we had manually patched in. We should add this back in later.
> sims/external/gem5: update to gem5 23.1

- experiments/simbricks/orchestration/experiment/experiment_output.py
This removes automatically sorting the keys that I introduced in #97, which means that instead, attributes are serialized in the order they are defined in. With this change, we can guarantee that at a glance information like start and end time are readable directly at the top of the JSON file.
> orchestration/experiment_output: fix key order in output JSON

- doc/simbricks-text-horizontal.svg
- doc/simbricks.svg
For some reason the new logo defaults to 0x0 px in the sphinx theme.
> doc: fix logo size to full width of container

- doc/requirements.txt
- docker/Dockerfile.buildenv
- docker/rules.mk
Otherwise make documentation fails in the devcontainer.
> docker: add missing breathe package to buildenv image

- sims/nic/i40e_bm/headers.h
- sims/nic/i40e_bm/i40e_adminq.cc
- sims/nic/i40e_bm/i40e_bm.cc
- sims/nic/i40e_bm/i40e_bm.h
- sims/nic/i40e_bm/i40e_lan.cc
- sims/nic/i40e_bm/i40e_ptp.cc
- sims/nic/i40e_bm/rules.mk
Adds support for hardware timestamping to the nic behavioral model. The actual changes are cherry-picked from the splitsim branch.
> sims/nic/i40e_bm: PTP support (PHC, rx/tx timestamping)

- lib/simbricks/axi/axi_subordinate.hh
- lib/simbricks/axi/axil_manager.hh
I stumbled across this while trying to integrate xsim. @q713 This possibly also fixes your issues with the new corundum version.
Tested with JPEG decoder and VTA.
> lib/simbricks/axil_manager: fix `step_apply()` sometimes being skipped 

- experiments/simbricks/orchestration/nodeconfig.py
- experiments/simbricks/orchestration/runners.py
We should pass an additional experiment environment variable to the function config_file(...) of the NodeConfig class in experiments/simbricks/orchestration/nodeconfig allowing to properly define paths to needed resources.
> experiments/simbricks/orchestration/nodeconfig: config_files env parameter

- symphony/runtime/simbricks/runtime/runs/local.py
Mark simulators that we wait for properly as terminated once they exit using the local runtime callbacks.
> fix terminating of simulations with local runtime
