simbricks/simbricks

docker/Dockerfile.min

Forgot to make this edit in #3.

fix Dockerfile.min build error

---

CONTRIBUTING.md

This adds a first draft for the contributing guide. Let's iterate on this but for now better to have something than nothing at all. :-)

CONTRIBUTING.md: add initial draft for contribution guide

---

.devcontainer.json
README.md

Improve Documentation for VS Code Dev Containers And Automatically Pull Required Docker Image

---

.github/workflows/lint-clang-format.yml
.github/workflows/lint-cpplint.yml

add GitHub action for cpplint and clang-format

---

experiments/simbricks/experiments.py
experiments/simbricks/runtime/distributed.py
experiments/simbricks/simulators.py

Python type-checking should now pass. Closes #22.

fix auto_dist missing nic attribute on Experiment and HostSim

---

experiments/run.py

With this, all Github Actions should pass.

fix failing typechecking for ctrl+c handling

---

lib/simbricks/base/if.c

SimbricksBaseIfInit: sanity check sync interval against latency

lib/base/if: extended SimbricksBaseIfInit #16

---

.pylintrc
experiments/pyexps/log_parser.py
experiments/simbricks/orchestration/exectools.py
experiments/simbricks/orchestration/experiments.py
experiments/simbricks/orchestration/runtime/local.py
experiments/simbricks/orchestration/runtime/slurm.py
experiments/simbricks/orchestration/simulators.py

Fix the failing pylint tests, also update pylint config to avoid warnings.

Fix overgeneral exceptions (#53)

---

Makefile
lib/simbricks/base/if.c

Fix clang format to produce errors in lint target

---

experiments/simbricks/orchestration/runtime/slurm.py

Thanks @Kaufi-Jonas, for already having a fix laying around. :-)

Fix python typecheck warning in slurm runtime

---

sims/nic/i40e_bm/i40e_bm.cc
sims/nic/i40e_bm/i40e_bm.h
sims/nic/i40e_bm/i40e_lan.cc
sims/nic/i40e_bm/i40e_queues.cc
sims/nic/i40e_bm/logger.cc

new linux driver versions need this.

i40e_bm: support for 16b rx descriptors

---

experiments/run.py
experiments/simbricks/orchestration/experiment/experiment_environment.py

There are now no more inline functions and a proper main function instead of top-level code. Functionality-wise, nothing was changed. Code was only rearranged.

experiments/run.py: improve readability

---

lib/simbricks/nicbm/nicbm.cc
lib/simbricks/nicbm/nicbm.h
sims/net/switch/net_switch.cc

I rebased the commits from https://github.com/simbricks/simbricks/pull/17 onto the current version of main, changed their commit messages and ran the auto-formatter.

more information in SIGUSR1 debug prints in nicbm and net_switch

---

README.md

This is based on our recent HackerNews Post and the description on our website.

README: tweak intro and include concrete use-cases

---

.github/workflows/lint-clang-format.yml
.github/workflows/lint-cpplint.yml
.github/workflows/lint-python.yml
.github/workflows/pre-commit.yml
.github/workflows/typecheck-python.yml
.pre-commit-config.yaml
experiments/pyexps/sysbench_memory.py
experiments/simbricks/orchestration/experiments.py
experiments/simbricks/orchestration/nodeconfig.py
experiments/simbricks/orchestration/proxy.py
experiments/simbricks/orchestration/runtime/common.py
experiments/simbricks/orchestration/simulators.py
requirements.txt

This includes adding a requirements.txt for the Python packages required for linting. In the future, additional packages that our orchestration framework requires also go in here.
The pylint action that currently fails will be fixed by #117.
Closes #52.

GitHub Actions: fix and update versions of all things involved

---

lib/simbricks/nicbm/nicbm.cc
lib/simbricks/nicbm/nicbm.h
lib/utils/log.h

+ lib/utils/log: Simple logging utility for use inside SimBricks.
+ lib/simbricks/nicbm/nicbm: Make use of simple logging lib to allow for directly logging into files (This is necessary for usage alongside Columbo).

Simple Logging utility for SimBricks

---

.gitmodules
docker/Dockerfile.buildenv
experiments/pyexps/qemu_udp_single.py
experiments/simbricks/orchestration/simulators.py
sims/external/rules.mk
sims/net/p4/basic.json

Adding SimBricks integration for P4 reference behavior model BMV2. Functionality verified using qemu_udp_single experiment.
To-dos:
- Add synchronization support
- Add p4c support to generate simple switch from p4 source code

BMV2 Integration

---

experiments/simbricks/orchestration/simulators.py

Parametrize P4 path in BMV2Net simulator

bmv2: move p4 path to a BMV2Net parameter

---

.github/workflows/typecheck-python.yml
Makefile
symphony/cli/pyproject.toml
symphony/cli/requirements.txt
symphony/client/pyproject.toml
symphony/client/requirements.txt
symphony/local/pyproject.toml
symphony/local/requirements.txt
symphony/orchestration/pyproject.toml
symphony/orchestration/requirements.txt
symphony/pyproject.toml
symphony/requirements.txt
symphony/rules.mk
symphony/runner/pyproject.toml
symphony/runner/requirements.txt
symphony/runtime/pyproject.toml
symphony/runtime/requirements.txt
symphony/schemas/pyproject.toml
symphony/schemas/requirements.txt
symphony/utils/pyproject.toml
symphony/utils/requirements.txt

- Added typechecking configurations to our new packages 
- Adjusted the github actions to use the new Makefile targets to trigger the typechecking

Typechecking

---

symphony/runner/simbricks/runner/main_runner/plugins/docker_plugin.py
symphony/runner/simbricks/runner/main_runner/plugins/plugin.py

Add configuration options to the docker fragment executor plugin, such as the docker image or allow and deny lists to configure allowed docker images.

symphony/runner: add more configuration options to docker plugin

---

experiments/minimal_net.py
experiments/minimal_net_dist.py
experiments/simple_demo.py
symphony/orchestration/simbricks/orchestration/instantiation/base.py
symphony/orchestration/simbricks/orchestration/simulation/host.py
symphony/orchestration/simbricks/orchestration/system/__init__.py
symphony/orchestration/simbricks/orchestration/system/base.py
symphony/orchestration/simbricks/orchestration/system/disk_images.py
symphony/orchestration/simbricks/orchestration/system/host/__init__.py
symphony/orchestration/simbricks/orchestration/system/host/app.py
symphony/orchestration/simbricks/orchestration/system/host/base.py

Hosts and disk images no longer necessarily have a one-to-one mapping, so that one image can be shared by multiple hosts.

Make disk images independent of hosts

---

sims/external/rules.mk
symphony/orchestration/simbricks/orchestration/simulation/pcidev.py
symphony/orchestration/simbricks/orchestration/system/host/app.py
symphony/orchestration/simbricks/orchestration/system/host/base.py
symphony/orchestration/simbricks/orchestration/system/pcie.py

Depends on: https://github.com/simbricks/femu/pull/1

Femu integration with new Orch. Framework
